In [1]:
import jax 
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt
import jaxopt

In [35]:
# Maybe not giving enough constraints? The inequalities are equalities after optimization through the multipliers...
# The dual fulfills the constraints, but do not optimize the objective function...
def f(params):
    Q_0 = jnp.array([[1, 0], [0, 9]])
    P_1 = -jnp.array([2, 1])
    P_2 = -jnp.array([1, 3])
    P_3 = -jnp.array([1, 0])
    P_4 = -jnp.array([0, 1])
    P = params[0]*P_1 + params[1]*P_2# + params[2]*P_3 + params[3]*P_4
    c_1 = 1
    c_2 = 1
    c = params[0]*c_1 + params[1]*c_2
    x = -0.5*jnp.linalg.inv(Q_0)@P
    D = x.T@Q_0@x + P@x + c
    return -D#, x.T@Q_0@x + P@x, x

In [42]:
og_params = jnp.array([-1., 0.]).astype("float32")

In [44]:
f(params), params

(Array(-0.51970756, dtype=float32),
 Array([-0.22003627,  1.2391565 ], dtype=float32))

In [43]:
optimizer = jaxopt.GradientDescent(f, maxiter = 1)
params = og_params.copy()
for i in range(15):
    print(-f(params))
    params, state = optimizer.run(params)

-2.0277777
0.25076622
0.45818067
0.48113534
0.49120623
0.5029161
0.5074427
0.5124742
0.5145209
0.51667607
0.5176078
0.5185273
0.51895475
0.51934516
0.5195429


In [58]:
Q = jnp.array([[1, 0], [0, 9]])
P = jnp.array([[2, 1],[1, 3]])
ideal_x = jnp.array([0.5, 1/6])
Q_0 = jnp.array([[1, 0], [0, 9]])
P_1 = -jnp.array([2, 1])
P_2 = -jnp.array([1, 3])
P_3 = -jnp.array([1, 0])
P_4 = -jnp.array([0, 1])
P = params[0]*P_1 + params[1]*P_2 + params[2]*P_3 + params[3]*P_4
-0.5*jnp.linalg.inv(Q_0)@P, params

(Array([4.397905e+09, 4.608470e+08], dtype=float32),
 Array([2.8377508e+09, 1.7720723e+09, 1.3482360e+09, 1.4127874e+08],      dtype=float32))